spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm111 # jdbc:mysql://<你的MySQL Host, 通常是localhost>:<你的MySQL端口, 通常3306>
    username: root # <你的MySQL账号, 请保证有足够的权限>
    password: 123456 # <你的MySQL密码>
    driver-class-name: com.mysql.jdbc.Driver
swagger:
  enabled: true